# Generated by Django 4.1.3 on 2023-01-10 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app13', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Signup',
            new_name='Register',
        ),
    ]
