# Generated by Django 4.1.3 on 2023-01-10 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app13', '0002_rename_signup_register'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ImageName', models.CharField(max_length=10)),
                ('Photo', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('Price', models.IntegerField()),
            ],
        ),
    ]
